build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels bashtage
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy h5py sphinx matplotlib pandas networkx cffi jupyter psutil sqlalchemy ipykernel ipywidgets"
  - activate test-environment
  - export GIT_LFS_SKIP_SMUDGE=1
  - pip install git+https://github.com/BBN-Q/bbndb.git
  - pip install git+https://github.com/BBN-Q/QGL.git@develop
  - pip install git+https://github.com/spatialaudio/nbsphinx.git@master
  - pip install pyvisa coveralls scikit-learn pyusb future python-usbtmc setproctitle progress
  - export GIT_LFS_SKIP_SMUDGE=0
  - export PYTHONPATH=$PYTHONPATH:$PWD/src

test_script:
  - coverage run -m unittest discover -v test
  