name: auspex
channels:
  - bbn-q
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - matplotlib
  - h5py
  - numpy
  - scipy
  - scikit-learn
  - ruamel.yaml
  - PyVISA
  - tqdm
  - pandas
  - networkx
  - cffi
  - psutil
  - pip
     - "--editable=git+https://github.com/bbn-q/qgl.git@load-from-yaml#egg=qgl"
     - "--editable=git+https://github.com/bbn-q/adapt.git@master#egg=adapt"
